# Generated by Django 4.1.7 on 2023-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='title',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='RFID',
            field=models.IntegerField(default=0),
        ),
    ]
