# Generated by Django 4.1.7 on 2023-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_c02_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='RFID',
            field=models.IntegerField(default=0),
        ),
    ]
