# Generated by Django 4.1.7 on 2023-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_lot_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='RFID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lotsizes',
            name='num_spaces',
            field=models.IntegerField(default=1),
        ),
    ]
