# Generated by Django 4.1.7 on 2023-02-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_lot_rfid_alter_lotsizes_num_spaces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lot',
            new_name='C02',
        ),
    ]
