# Generated by Django 4.1.7 on 2023-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_lot_c02'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot', models.CharField(max_length=200)),
                ('RFID', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='LotSizes',
            new_name='LotSize',
        ),
        migrations.DeleteModel(
            name='C02',
        ),
    ]
